export default function ReportFooter()
{
	return (
		<div
			className="hidden print:flex fixed bottom-0 left-0 w-full justify-between items-center pt-4 border-t border-black/20 text-xs text-black/60 bg-white">
			<p>Yusr Company Ltd. © { new Date().getFullYear() }</p>
			<p>Generated by Yusr System</p>
			<p>Confidential Document</p>
		</div>
	);
}