import { YusrSystemPermissionsResources } from "yusr-ui";


export const SystemPermissionsResources = {
	...YusrSystemPermissionsResources,
	Invoices: "Invoices",
	Quotations: "Quotations",
	Vouchers: "Vouchers",
	Accounts: "Accounts",
	BalanceTransfers: "BalanceTransfers",
	PaymentMethods: "PaymentMethods",
	Partners: "Partners",
	FiscalYears: "FiscalYears",
	FiscalPeriods: "FiscalPeriods",
	FiscalYearClose: "FiscalYearClose",
	FiscalYearReopen: "FiscalYearReopen",
	Items: "Items",
	Brands: "Brands",
	Categories: "Categories",
	ItemTransfers: "ItemTransfers",
	ItemsSettlements: "ItemsSettlements",
	Stocktakings: "Stocktakings",
	CostAdjustments: "CostAdjustments",
	Units: "Units",
	PricingMethods: "PricingMethods",
	Stores: "Stores",
	Taxes: "Taxes",
	PosTerminals: "PosTerminals",
	PosSessions: "PosSessions",
	Obligations: "Obligations",
	InvoiceAddSettlement: "InvoiceAddSettlement",
	InvoiceShowProfit: "InvoiceShowProfit",
	InvoiceShowItemProfit: "InvoiceShowItemProfit",
	InvoiceSellBelowSellingPrice: "InvoiceSellBelowSellingPrice",
	InvoiceSellBeyondAvailableQuantity: "InvoiceSellBeyondAvailableQuantity",
	InvoiceSell: "InvoiceSell",
	InvoicePurchase: "InvoicePurchase",
	AccountShowBalance: "AccountShowBalance",
	ReportInvoice: "ReportInvoice",
	ReportInvoiceList: "ReportInvoiceList",
	ReportVoucher: "ReportVoucher",
	ReportVoucherList: "ReportVoucherList",
	ReportAccountStatement: "ReportAccountStatement",
	ReportPartnerStatement: "ReportPartnerStatement",
	ReportAccountList: "ReportAccountList",
	ReportBalanceTransfer: "ReportBalanceTransfer",
	ReportItemStatement: "ReportItemStatement",
	ReportItemList: "ReportItemList",
	ReportItemMovement: "ReportItemMovement",
	ReportItemTaxStatement: "ReportItemTaxStatement",
	ReportItemTransfer: "ReportItemTransfer",
	ReportBalanceSheet: "ReportBalanceSheet",
	ReportVatReturn: "ReportVatReturn",
	ReportPl: "ReportPl",
	ReportSalesProfitability: "ReportSalesProfitability",
	ReportTaxAudit: "ReportTaxAudit",
	ReportStocktaking: "ReportStocktaking",
	ReportItemSettlement: "ReportItemSettlement",
	ReportItemBarcode: "ReportItemBarcode",
	ReportStockValuation: "ReportStockValuation",
	ReportLowStock: "ReportLowStock"
} as const;